{% set name = "langchain" %}
{% set version = "0.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/langchain-{{ version }}.tar.gz
    sha256: 867f6add370c1e3911b0e87d3dd0e36aec1e8f513bf06131340fe8f151d89dc5

build:
  entry_points:
    - langchain-server = langchain.server:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8,<4.0
    - langchain-core >=0.2.6,<0.3.0
    - langchain-text-splitters >=0.2.0,<0.3.0
    - langsmith >=0.1.17,<0.2.0
    - pydantic >=1,<3
    - sqlalchemy >=1.4,<3
    - requests >=2.0.0,<3.0.0
    - pyyaml >=5.3
    - numpy >=1.0.0,<2.0.0
    - aiohttp >=3.8.3,<4.0.0
    - tenacity >=8.1.0,<9.0.0
    - async-timeout >=4.0.0,<5.0.0
  run_constrained:
    # based on https://github.com/langchain-ai/langchain/blob/master/libs/langchain/extended_testing_deps.txt
    - jsonschema >=4.22.0,<5
    - numexpr >=2.8.6,<3
    - rapidfuzz >=3.1.1,<4
    - aiosqlite >=0.19.0,<0.20
    # copied from langchain-openai-feedstock
    - openai >=1.26.0,<2.0.0
    - tiktoken >=0.7,<1
    # copied from langchain-anthropic-feedstock
    - anthropic >=0.28.0,<1
    - defusedxml <0.8.0,>=0.7.1
    # copied from langchain-fireworks-feedstock and langchain-together-feedstock
    - fireworks-ai >=0.13.0
    - openai >=1.10.0,<2.0.0
    - requests >=2.0.0,<3.0.0
    - aiohttp >=3.9.1,<4.0.0
    # copied from langchain-mistralai-feedstock
    - tokenizers >=0.15.1,<1
    - httpx >=0.25.2,<1
    - httpx-sse >=0.3.1,<1
    # copied from langchain-groq-feedstock
    - groq >=0.4.1,<1

test:
  imports:
    - langchain
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/langchain-ai/langchain
  summary: Building applications with LLMs through composability
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - baskaryan
    - hinthornw
    - efriis
    - YYYasin19
    - pavelzw
    - jan-janssen
