{% set name = "langchain" %}
{% set version = "0.3.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/langchain-{{ version }}.tar.gz
    sha256: 1204d67f8469cd8da5621d2b39501650a824d4c0d5a74264dfe3df9a7528897e

build:
  entry_points:
    - langchain-server = langchain.server:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }}{{ python_max }}
    - langchain-core >=0.3.31,<0.4.0
    - langchain-text-splitters >=0.3.3,<0.4.0
    - langsmith >=0.1.17,<0.4
    - pydantic >=2.7.4,<3.0.0
    - sqlalchemy >=1.4,<3
    - requests >=2.0.0,<3.0.0
    - pyyaml >=5.3
    - numpy >=1.22.4,<3  # [python_max == ""]
    - numpy >=1.22.4,<2  # [python_max != ""]
    - aiohttp >=3.8.3,<4.0.0
    - tenacity >=8.1.0,!=8.4.0,<10
    - async-timeout >=4.0.0,<5.0.0
  run_constrained:
    # based on https://github.com/langchain-ai/langchain/blob/master/libs/langchain/extended_testing_deps.txt
    - jsonschema >=4.22.0,<5
    - numexpr >=2.8.6,<3
    - rapidfuzz >=3.1.1,<4
    - aiosqlite >=0.19.0,<0.20
    # copied from langchain-openai-feedstock
    - openai >=1.26.0,<2.0.0
    - tiktoken >=0.7,<1
    # copied from langchain-anthropic-feedstock
    - anthropic >=0.28.0,<1
    - defusedxml <0.8.0,>=0.7.1
    # copied from langchain-fireworks-feedstock and langchain-together-feedstock
    - fireworks-ai >=0.13.0
    - openai >=1.10.0,<2.0.0
    - requests >=2.0.0,<3.0.0
    - aiohttp >=3.9.1,<4.0.0
    # copied from langchain-mistralai-feedstock
    - tokenizers >=0.15.1,<1
    - httpx >=0.25.2,<1
    - httpx-sse >=0.3.1,<1
    # copied from langchain-groq-feedstock
    - groq >=0.4.1,<1

test:
  imports:
    - langchain
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/langchain-ai/langchain
  summary: Building applications with LLMs through composability
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - dlqqq
    - baskaryan
    - hinthornw
    - efriis
    - YYYasin19
    - pavelzw
    - jan-janssen
