{% set name = "langchain" %}
{% set version = "0.3.25" %}
{% set build = 1 %}
{% set python_max = ",<3.13a0" if python_min == "3.9" else "" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/langchain-{{ version }}.tar.gz
    sha256: a1d72aa39546a23db08492d7228464af35c9ee83379945535ceef877340d2a3a

build:
  entry_points:
    - langchain-server = langchain.server:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: {{ build }}
  string: "pymin{{ python_min|replace('.', '') }}_h{{ PKG_HASH }}_{{ build }}"

requirements:
  host:
    - python {{ python_min }}
    - pdm-backend
    - pip
  run:
    - python >={{ python_min }}{{ python_max }}
    - langchain-core <1.0.0,>=0.3.58
    - langchain-text-splitters <1.0.0,>=0.3.8
    - langsmith <0.4,>=0.1.17
    - pydantic <3.0.0,>=2.7.4
    - sqlalchemy <3,>=1.4
    - requests <3,>=2
    - pyyaml >=5.3
    {% if python_max == "" %}
    - numpy >=2.1.0
    {% else %}
    - numpy >=1.26.4
    {% endif %}
    - aiohttp <4.0.0,>=3.8.3
    - tenacity !=8.4.0,<10,>=8.1.0
    - async-timeout >=4.0.0,<5.0.0
  run_constrained:
    # based on https://github.com/langchain-ai/langchain/blob/master/libs/langchain/extended_testing_deps.txt
    - jsonschema >=4.22.0,<5
    - numexpr >=2.8.6,<3
    - rapidfuzz >=3.1.1,<4
    - aiosqlite >=0.19.0,<0.20
    # copied from langchain-openai-feedstock
    - openai >=1.26.0,<2.0.0
    - tiktoken >=0.7,<1
    # copied from langchain-anthropic-feedstock
    - anthropic >=0.28.0,<1
    - defusedxml <0.8.0,>=0.7.1
    # copied from langchain-fireworks-feedstock and langchain-together-feedstock
    - fireworks-ai >=0.13.0
    - openai >=1.10.0,<2.0.0
    - requests >=2.0.0,<3.0.0
    - aiohttp >=3.9.1,<4.0.0
    # copied from langchain-mistralai-feedstock
    - tokenizers >=0.15.1,<1
    - httpx >=0.25.2,<1
    - httpx-sse >=0.3.1,<1
    # copied from langchain-groq-feedstock
    - groq >=0.4.1,<1

test:
  imports:
    - langchain
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/langchain-ai/langchain
  summary: Building applications with LLMs through composability
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - dlqqq
    - baskaryan
    - hinthornw
    - ccurme
    - sydney-runkle
    - YYYasin19
    - pavelzw
    - jan-janssen
